install.packages("caret")
library(caret)
library(car)
library(leaps)
population<-read.csv("~/Desktop/Population.csv", sep=",", header=T)
population$Province<-as.factor(population$Province)
scatterplotMatrix(population[1:5],regLine = F, groups = population$Province, by.groups = T, smooth = F, diagonal = list(method="boxplot"), legend=list(coords="bottom"), cex.labels=1.5)
model<-lm(Population~.,data=population)
summary(model)
gdp_model<-lm(Population~GDP_PC+Province, data = population)
income_model<-lm(Population~Income+Province, data = population)
life_exp_model<-lm(Population~Life_Exp+Province, data = population)
empl_model<-lm(Population~Empl_Rate+Province, data=population)
summary(gdp_model)
summary(income_model)
summary(life_exp_model)
summary(empl_model)
preproc<-preProcess(population[,c(1:5)], method = c("range"))
norm_pop<-predict(preproc,population[,c(1:5)])
norm_pop$Province<-population$Province
model_full<-lm(Population~.,data=norm_pop)
summary(model_full)
selected<-regsubsets(Population~., data = norm_pop, method = "exhaustive", nvmax = 12)
selected_summary<-summary(selected)
selected_summary$which
p<-c(1:12)
Cp<-selected_summary$cp
plot(x=p, y=Cp, xlim = range(8,12),ylim=range(0,100), main = "Cp against p for Model Selection")
abline(0,1)
selected_summary$adjr2
rmse<-function(u,v) sqrt(mean((u-v)^2))
random_idx<-sample.int(27)
train<-norm_pop[random_idx,]
test<-norm_pop[--random_idx,]
train0<-lm(Population~Province, data = train)
train1<-lm(Population~Life_Exp+Province, data = train)
train2<-lm(Population~Life_Exp+Empl_Rate+Province, data = train)
train3<-lm(Population~Life_Exp+Empl_Rate+Income+Province, data = train)
train4<-lm(Population~Life_Exp+Empl_Rate+Income+GDP_PC+Province, data = train)
predict0<-predict(train0,test)
predict1<-predict(train1,test)
predict2<-predict(train2,test)
predict3<-predict(train3,test)
predict4<-predict(train4,test)
rmse0<-rmse(test$Population, predict0)
rmse1<-rmse(test$Population, predict1)
rmse2<-rmse(test$Population, predict2)
rmse3<-rmse(test$Population, predict3)
rmse4<-rmse(test$Population, predict4)
rmse_summary<-c(rmse0,rmse1,rmse2,rmse3,rmse4)
rmse_summary
final_model<-lm(formula = Population ~ Life_Exp + Empl_Rate + Province, data = norm_pop)
